### ISSUE TITLE
[DOCS](fix):  Step 7 in README file needs clarity

### ISSUE THREAD

**Issue by goobric** [open-sauced/guestbook#115]
### Type of feature

📝 Documentation

### Current behavior

Semantic reading of step 7.
A user would have already run the command:
 ' git commit -am "your message" '
 
before reading: 'You can skip this step(7) if you use the CLI..

### Suggested solution

7. If you used the CLI tool method in step 6, to add yourself to the guestbook, skip this step; otherwise:
Add and commit your changes by running this command:
' git commit -am "your message" '

Change "Your message" to your own message. For example, "Add Alice to the guestbook".

please assign me to update instruction step 7 of the README.md file

### Additional context

I hope that this reads better sematically

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
Hi @goobric. Let's focus on adding you to the guestbook first :)

**Comment by ToobaJamal** [comment]
Hey @CBID2, I would like to work on this issue :)

**Comment by CBID2** [comment]
Hey @goobric. You can start now! :)
