### ISSUE TITLE
Feature: add a CODEOWNERS file

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/guestbook#132]
### Type of feature

🍕 Feature

### Current behavior

There is not a CODEOWNERS file.

### Suggested solution

We can essentially replicate what we have in the `pizza-verse` repo: https://github.com/open-sauced/pizza-verse/blob/main/.github/CODEOWNERS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
I'll do it @BekahHW! 😊
