### ISSUE TITLE
feature: Add docs contributing guidelines

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/guestbook#138]
There are two types of contrubutions to this repo: 
1. adding yourself (according to chapter directions).
2. updating the repo to make it a better contributor experience.

We've been successful with the docs for the first. Let's improve the docs for the second.

To do this, we need to explain how to run the project locally: https://github.com/open-sauced/intro/blob/main/CONTRIBUTING.md.

I'm in favor of adding this CONTRIBUTING.md file to our repo and linking in our readme with an explanation that if you're interested in contributing to improve this course, please create an issue and refer to this guide.

**Comment by codewithjazzy** [comment]
.take

**Comment by codewithjazzy** [comment]
I can .take this one

**Comment by CBID2** [comment]
> I can .take this one

Go right ahead @codewithjazzy
