### ISSUE TITLE
Bug: remove extra `tr`

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/guestbook#139]
### Describe the bug

We have an extra `tr`

![image](https://github.com/open-sauced/guestbook/assets/34313413/f63b3545-3f37-4311-9f7d-b773755a89b5)

### Steps to reproduce

I haven't had a change to look at the code, but you should be able to find it in the readme. Remove the extra tr.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
@BekahHW, I assigned this as a good first issue. I hope you don't mind.

**Comment by codewithjazzy** [comment]
I can .take this one

**Comment by bL34cHig0** [comment]
Could I please be assigned to this issue? Thank you.

**Comment by CBID2** [comment]
> Could I please be assigned to this issue? Thank you.

Done @bL34cHig0

**Comment by bL34cHig0** [comment]
Thanks @CBID2. I went through the Readme file and it seems the extra `tr` tag has been removed.

**Comment by CBID2** [comment]
> Thanks @CBID2. I went through the Readme file and it seems the extra `tr` tag has been removed.

Ooh you're correct
@bL34cHig0. I'll close this issue now.

**Comment by CBID2** [comment]
@bL34cHig0, this issue is free for the taking if you want: https://github.com/open-sauced/guestbook/issues/138

**Comment by bL34cHig0** [comment]
Thanks @CBID2 but there's no need for me to take credit for this issue. I genuinely appreciate your support.

**Comment by CBID2** [comment]
> Thanks @CBID2 but there's no need for me to take credit for this issue. I genuinely appreciate your support.

Oh no I'm recommending issues you can work @CBID2

**Comment by bL34cHig0** [comment]
Oh I truly apologize for the misunderstanding @CBID2. Sure, I'll take a look at it. Thank you.
