### ISSUE TITLE
Bug: Translation Guide updates 

### ISSUE THREAD

**Issue by CBID2** [open-sauced/guestbook#144]
### Describe the bug

I noticed two issues in regards to the translation guide:
1. The guide is not hyperlinked in second bullet point in [the Contributing to this Repository section of the README file](https://github.com/open-sauced/guestbook/blob/main/README.md#-contributing)
2. The`i18tn-guidelines.md` file is labeled incorrectly. 

## Issue 1
1. Go to the second bullet point in [the Contributing to this Repository section of the README file](https://github.com/open-sauced/guestbook/tree/main#readme)
2. Try to click on `community guidelines` 
3. Nothing happens 

## Issue 2
1. Go to [the Code](https://github.com/open-sauced/guestbook) tab
2. Go to [the`i18tn-guidelines.md` file](https://github.com/open-sauced/guestbook/blob/main/i18tn-guidelines.md) and see the wrong file name
 

### Browsers

Other (add additional context)

### Additional context (Is this in dev or production?)

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jdwilkin4** [comment]
I would be interested in working on this 😃

**Comment by CBID2** [comment]
> I would be interested in working on this 😃

Sure @jdwilkin4! :) You're assigned! :)
