### ISSUE TITLE
Bug: Unknown contribution type error when trying to run the npm run contributors:add command

### ISSUE THREAD

**Issue by jdwilkin4** [open-sauced/guestbook#155]
### Describe the bug

I tried running the `npm run contributors:add` command locally, and ran into this error

Error: Unknown contribution type web development for contributor

Here is the complete screenshot

<img width="1371" alt="Screenshot 2023-10-25 at 12 06 59 PM" src="https://github.com/open-sauced/guestbook/assets/67210629/11d41471-00c5-4335-ab7f-0897025b6086">

The error is happening because web development is not a valid entry for the contributions array

```
 "contributions": [
        "web development"
      ]
```

the fix would be to change that to `code ` since that is a valid entry

```
 "contributions": [
        "code"
      ]
```

But also, for the long term it might be nice to have an additional check in place to double check that the contributions array only holds valid values.
That way if a user tries to contribute to the guestbook manually with an invalid value, then the check will catch that. 

### Steps to reproduce

1. got the guestbook repo locally
2. pull down the latest changes from main
3. create a new branch
4. run the `npm run contributors:add` command
5. see the error

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jdwilkin4** [comment]
it looks like this error also affects the generate command to

<img width="1368" alt="Screenshot 2023-10-25 at 12 29 19 PM" src="https://github.com/open-sauced/guestbook/assets/67210629/3f27afc9-f26f-48d1-8a79-f06985d82f7d">

**Comment by CBID2** [comment]
Hey @jdwilkin4. Have you checked this locally?

**Comment by jdwilkin4** [comment]
yes, I have included screenshots in the post above 👍

**Comment by adiati98** [comment]
Hey @jdwilkin4,
Thank you for spotting the bug!

I've tried it locally, and yes. It seems that this was a manual entry. And "web development" is not included in the list of [emoji key and contribution type](https://allcontributors.org/docs/en/emoji-key).

The solution is precisely what you described, by replacing the "web development" with "code".

And thanks for the suggestion to have the additional check. We will take that into account. :)

Do you want to work on this issue?

**Comment by jdwilkin4** [comment]
@adiati98 

Sure, I can create a PR for that fix 👍

**Comment by adiati98** [comment]
Awesome! Thank you, @jdwilkin4!

**Comment by BekahHW** [comment]
Thanks, @jdwilkin4!
