### ISSUE TITLE
docs: Add extra instruction for manual entry and improve README

### ISSUE THREAD

**Issue by adiati98** [open-sauced/guestbook#171]
## Description

When contributors add themselves manually, they should follow the [emoji key and contribution types](https://allcontributors.org/docs/en/emoji-key). Not following this list will break the process of generating README and the following PRs.

As there will be changes in the README, we might as well improve it.

## Suggestion

- Add an instruction as a warning to fill in the value strictly from the contribution types list.
- Add OpenSauced's banner for consistency throughout repositories.
- Change blob links to file's links.
- Fix and adjust wordings for clarity if necessary.

**Comment by CBID2** [comment]
Hey @adiati98. Can I do this one? :) lol, I haven't done the docs for the repo in a while.

**Comment by adiati98** [comment]
Hey @CBID2 
I've made the changes locally and plan to push it tomorrow because I want to reread it with fresh eyes. 😊

But you can review it! 🙂

**Comment by CBID2** [comment]
> Hey @CBID2 
> I've made the changes locally and plan to push it tomorrow because I want to reread it with fresh eyes. 😊
> 
> But you can review it! 🙂

Ok @adiati98.
