### ISSUE TITLE
Feature: Add explanation to `git commit -am`

### ISSUE THREAD

**Issue by CBID2** [open-sauced/guestbook#179]
### Type of feature

📝 Documentation

### Current behavior

 Step 7 in [the Getting Started section of the README file](https://github.com/open-sauced/guestbook/blob/main/README.md#getting-started) uses `commit -am "Your message"`. However, it doesn't explain what that commit does. Since this repo is aimed at people who finished the intro course, contributors might not be too comfortable with using this command yet.  

### Suggested solution
Provide a brief explanation of this commit.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
@adiati98 and @BekahHW, I need your opinion on the solution. 
Then I'd like to .take this issue. Thank you! 😊

**Comment by CBID2** [comment]
.take

**Comment by adiati98** [comment]
@CBID2 as per discussion, we will keep the `git commit -am`. The earlier beginners in OSS learn about shortcut commands that can benefit them, the better.
And looking at the major type of contributions in this repo, this command is considered safer to use here than `git add .`  followed by `git commit -m` to avoid committing new files that aren't necessary.

However, we might want to briefly explain about the shortcut.

Here are some references to help you out:

- https://github.com/git-guides/git-commit#common-usages-and-options-for-git-commit
- https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--a
- https://www.freecodecamp.org/news/git-commit-command-explained/

Please also change the title of this issue to "docs: Add explanation to `git commit -am`" for better understanding.

Thank you! 🙂
