### ISSUE TITLE
docs: Move the content of "Getting Started" and "Update Branch & Resolve Conflicts" sections to Intro to Open Source course 

### ISSUE THREAD

**Issue by adiati98** [open-sauced/guestbook#197]
## Description

Outside of Hacktoberfest, most contributors who contribute to this repo are participants of our Intro to Open Source course. So I propose to remove the "Getting Started" and "Update Branch & Resolve Conflicts" sections and move them to the Intro to Open Source course. 

Moving these sections to the course will give 2 benefits:

1. As a one-stop-place of all course's docs for our participants.
2. When folks who don't take the course come to this repo, they would be sent to our course. That way, it can attracts folks to check out our course and potentially, recommend the course to others.

## Propose Solution

- Move the [Getting Started](https://github.com/open-sauced/guestbook?tab=readme-ov-file#getting-started) section from README to replace the content in the [Let's Get Practical](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=let39s-get-practical) section in the course.
- Move the [Keeping Branch Up to Date and Resolving Merge Conflicts](https://github.com/open-sauced/guestbook?tab=readme-ov-file#keeping-branch-up-to-date-and-resolving-merge-conflicts) from README to replace the [Merge Conflicts](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=merge-conflicts) section in the course.
- Link each section from "Intro to Open Source" course to the "Getting Started" and the "Keeping Branch Up to Date and Resolving Merge Conflicts" section in the README. 

## Note

This issue is depending on [this PR in the intro repository](https://github.com/open-sauced/intro/pull/100).

**Comment by adiati98** [comment]
@BekahHW I will start work on this and [this issue](https://github.com/open-sauced/intro/issues/99) on the `intro` repo if it's a go.
And no rush. 😊

**Comment by BekahHW** [comment]
Yes! Sorry, I thought I responded earlier.

**Comment by adiati98** [comment]
> Yes! Sorry, I thought I responded earlier.

No worries! Thanks for the response. I'll work on them. 😊
