### ISSUE TITLE
docs: more adjustments to the PR template

### ISSUE THREAD

**Issue by CBID2** [open-sauced/guestbook#203]
### Type of feature

📝 Documentation

### Current behavior

When filling out the form for docs-related PRs, I found myself struggling with answering some of the questions and connecting the corresponding issue to it. A similar phenomenon could happen for people who want to do translation contributions or improve the directions in the README and Contributing files.  

### Suggested solution

1. Put a `[] Not applicable` checkbox in the [Contributors Checklist section](https://github.com/open-sauced/guestbook/blob/main/.github/PULL_REQUEST_TEMPLATE.md#contributors-checklist-check-all-applicable)
2. Put a `[] 📝 CONTRIBUTING.md` checkbox in the [Added to Documentation section](https://github.com/open-sauced/guestbook/blob/main/.github/PULL_REQUEST_TEMPLATE.md#added-to-documentation). 
3. Put a `## Closes Issue` section after the [What Type of PR is this? section](https://github.com/open-sauced/guestbook/blob/main/.github/PULL_REQUEST_TEMPLATE.md#what-type-of-pr-is-this-check-all-applicable)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
> @CBID2 when would 1. be not applicable?
> 
> I wonder if we need the documentation section at all. What might be more effective is after the getting started section having a question like:
> 
> 
> 
> ## How have you contributed to this repository?
> 
> - [ ] Updated documentation (You're finished with the PR template!)
> 
> - [ ] Added myself as a contributor (move on the the next section)
> 
> 
> 
> 3. Yes!!!

@BekahHW, 1 would be if contributors aren't adding their name to the guestbook. Like fixing a bug or updating other aspects of the repo(e.g. docs and adding features). Does that make more sense now?

**Comment by adiati98** [comment]
@CBID2

- I quite agree with @BekahHW not to have "What type of PR is this?" section (and maybe also "Added to documentation?" section).

    I might be wrong, but I think making the PR template focus on adding contributors to the guestbook is more effective here.
    This repo is rarely receiving documentation updates except from maintainers. For that purpose, we can always adjust the PR templates ourselves if necessary (like add link PR to the related issue, etc.) or create one from scratch.

- > 3. Put a `## Closes Issue` section after the [What Type of PR is this? section](https://github.com/open-sauced/guestbook/blob/main/.github/PULL_REQUEST_TEMPLATE.md#what-type-of-pr-is-this-check-all-applicable)

    We can always add this one although we usually creates issue only to update docs.

    In general, this repo doesn't require issue to add contributors. Except if we want to update the Contributing Guide and apply [the suggestion](https://github.com/open-sauced/guestbook/pull/202?notification_referrer_id=NT_kwDOArFIJ7M4ODM3OTIyNzY4OjQ1MTcyNzc1#issuecomment-1866550171) for contributors to learn and practice how to create an issue and link it to the PR. Do we want to do this?

**Comment by CBID2** [comment]
> @CBID2
> 
> 
> 
> - I quite agree with @BekahHW not to have "What type of PR is this?" section (and maybe also "Added to documentation?" section).
> 
> 
> 
>     I might be wrong, but I think making the PR template focus on adding contributors to the guestbook is more effective here.
> 
>     This repo is rarely receiving documentation updates except from maintainers. For that purpose, we can always adjust the PR templates ourselves if necessary (like add link PR to the related issue, etc.) or create one from scratch.
> 
> 
> 
> - > 3. Put a `## Closes Issue` section after the [What Type of PR is this? section](https://github.com/open-sauced/guestbook/blob/main/.github/PULL_REQUEST_TEMPLATE.md#what-type-of-pr-is-this-check-all-applicable)
> 
> 
> 
>     We can always add this one although we usually creates issue only to update docs.
> 
> 
> 
>     In general, this repo doesn't require issue to add contributors. Except if we want to update the Contributing Guide and apply [the suggestion](https://github.com/open-sauced/guestbook/pull/202?notification_referrer_id=NT_kwDOArFIJ7M4ODM3OTIyNzY4OjQ1MTcyNzc1#issuecomment-1866550171) for contributors to learn and practice how to create an issue and link it to the PR. Do we want to do this?

Good point @adiati98! :) Sure, I'll do it! :)

**Comment by BekahHW** [comment]
Yeah, @adiati98, I think we should add the issue thing to the intro course. It's a good way to get  contributors into a better flow of contributing.

**Comment by adiati98** [comment]
@BekahHW I'll create an issue and work on this. 👍

**Comment by CBID2** [comment]
So can we go ahead and merge this PR?
