### ISSUE TITLE
Docs: Remove "Adding a New Section to the Documentation" section

### ISSUE THREAD

**Issue by adiati98** [open-sauced/guestbook#207]
## Description

We have a section in the `CONTRIBUTING.md` called [Adding a New Section to the Documentation](https://github.com/open-sauced/guestbook/blob/main/CONTRIBUTING.md#adding-a-new-section-to-the-documentation).

This section is no longer needed as it's specific for intro repository and we have removed the subsections from this repo's Contributing Guide.

## Suggested solution

Remove the section from Contributing Guide.

Below is the code block for the section that needs to be removed:

https://github.com/open-sauced/guestbook/blob/d2629d634f9df8f973b178d962bd98dcd58ab2df/CONTRIBUTING.md?plain=1#L77-L80

**Comment by at-the-vr** [comment]
Hey 👋 I believe i have got the idea about `CONTRIBUTING.md` and was wondering if I can target #208 with the same PR as well since its the same task (`REMOVING` content off `CONTRIBUTING.md`)

If not I would like to assigned for this Issue only and get that work done 😄

**Comment by adiati98** [comment]
Hey @at-the-vr,

I'll assign you to this first. If no one takes it after you finish, let me know, and I'll assign it to you. 👍
