### ISSUE TITLE
Docs: Remove the "Running the Project Locally" from Contributing Guide

### ISSUE THREAD

**Issue by adiati98** [open-sauced/guestbook#208]
## Description

The content in the [Running the Project Locally](https://github.com/open-sauced/guestbook/blob/main/CONTRIBUTING.md#running-the-project-locally) section in the Contributing Guide is meant for the `intro` repo.

This project is not built on Docsify.

## Suggested solution

Remove the section from the Contributing Guideline.

Below are the code blocks for this section:

https://github.com/open-sauced/guestbook/blob/d2629d634f9df8f973b178d962bd98dcd58ab2df/CONTRIBUTING.md?plain=1#L37-L76

**Comment by CBID2** [comment]
> jumping to this Issue, can I take on this as well ?

Go for it @at-the-vr
