### ISSUE TITLE
Docs: Adjust wording in the Contributing Guide

### ISSUE THREAD

**Issue by adiati98** [open-sauced/guestbook#209]
## Description

As we are adjusting our Contributing Guide to be only be about contributing to improve this repository, we would also adjust some of the wording in the guide.

_Originally posted by @BekahHW in https://github.com/open-sauced/guestbook/pull/202#discussion_r1435283089_

## Suggested solution

- [ ] Add this sentence as an opening line for the guide.

  > This Contributing Guide will walk you through how to contribute to this project for bug fixes and features. If you want to contribute to the guestbook, please refer to [chapter five](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source) of the Intro to Open Source course.

- [ ] Fix the wording of step 3 in the "Setup the Project Locally" as below:
 
  > Navigate to and open the project in your code editor.

   https://github.com/open-sauced/guestbook/blob/d2629d634f9df8f973b178d962bd98dcd58ab2df/CONTRIBUTING.md?plain=1#L29

- [ ] Remove step 4 in the "Setup the Project Locally".

  https://github.com/open-sauced/guestbook/blob/d2629d634f9df8f973b178d962bd98dcd58ab2df/CONTRIBUTING.md?plain=1#L35

- [ ] Update the numbering to reflect the changes

> #### Method 2: Using Visual Studio Code (VS Code) Go Live Feature

**Comment by adiati98** [comment]
@BekahHW I need you to triage this issue before we remove the `needs-triage` label and open it for contribution.
Please add/remove anything necessary here.

Thank you!

**Comment by Arol15** [comment]
@adiati98 Can I take this?
