### ISSUE TITLE
docs: Clarity about screenshot 

### ISSUE THREAD

**Issue by CBID2** [open-sauced/guestbook#223]
### Type of feature

🍕 Feature

### Current behavior

Contributors have been skipping the screenshot section when filling out their PR form. It’s mostly likely due to assuming that’s it’s not required inspite of the course mentioning that it’s needed. 

### Suggested solution

1. Go the `.github` folder
2. Go to the `Pull Request` file 
3. On line 39, next to `Screenshot`, write "(*Required before Pull Request is Reviewed)" 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by ArvindParekh** [comment]
Hi, I'd be happy to help with this one.
.take

**Comment by CBID2** [comment]
Go right ahead @ArvindParekh
