### ISSUE TITLE
Feature: Add @JulesRules65 as a contributor

### ISSUE THREAD

**Issue by JulesRules65** [open-sauced/guestbook#225]
### Type of feature

📝 Documentation

### Current behavior

I want to do my first contribution to the roject

### Suggested solution

I would like to add my name to the contribution list

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
Go ahead @JulesRules65

**Comment by JulesRules65** [comment]
Added my name to the list of contributors and closing this issue.
