### ISSUE TITLE
Feature: add @chrisVCH as a contributor

### ISSUE THREAD

**Issue by chrisVCH** [open-sauced/guestbook#231]
### Type of feature

🍕 Feature

### Current behavior

I want to make my first contribution.

### Suggested solution

I would like to add myself as a contributor to the guestbook.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
Go ahead @chrisVCH

**Comment by chrisVCH** [comment]
Feature request acknowledged.
