### ISSUE TITLE
Docs: Update pull request template

### ISSUE THREAD

**Issue by adiati98** [open-sauced/guestbook#241]
> [!IMPORTANT]
> If you've worked on a good first issue in any of our [community repositories](https://docs.opensauced.pizza/contributing/opensauced-maintainers-guide/community-maintainers-guide/#opensauced-community-repositories) before, please refrain from taking this issue.
> We may remove you from the assignees and not accept your pull request if you choose to proceed.

## Description

We have updated the "[Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started)" section on our Intro to Open Source course as following:

- Adding contributors to the guestbook with CLI only.
- Encouraging contributors to learn how to create issues.

Therefore, we need to update the PR template to reflect this update.

Additionally, we also want to remind contributors to complete the PR form.

## Suggested Solution

- [ ] Add a comment on the first line with the copy below.

   ```markdown
   <!-- Please fill in all areas in this PR form. Incomplete PRs will be marked invalid and may be closed. -->
   ```

- [ ] Add a new section for related issues right after "What type of PR" section. Use the copy below.

```markdown
## Related Issues

<!-- 
Please use this format link issue numbers: Closes #123
More information: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword 
-->
```

- [ ] Update wording in the "Contributing Checklist" section with the below suggestion.

   ```diff
   - ## Contributors checklist (check all applicable)
   + ## Contributors checklist
   ```

   https://github.com/open-sauced/guestbook/blob/20aeca121bd3a794b5c4ec4611f1937b9ac31e5f/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L13

- [ ] Remove the below sections.

   https://github.com/open-sauced/guestbook/blob/20aeca121bd3a794b5c4ec4611f1937b9ac31e5f/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L20-L29

**Comment by safaanilatasoy** [comment]
.take

**Comment by safaanilatasoy** [comment]
.take

**Comment by adiati98** [comment]
Hey @safaanilatasoy,

Thank you for your interest in taking this issue! 

However, we only allow contributors to take **one** good first issue. Please read our [Contributing Guidelines](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues).

Because you've taken #246, we won't assign you to this issue or any good first issue in one of our [community repositories](https://docs.opensauced.pizza/contributing/opensauced-maintainers-guide/community-maintainers-guide/#opensauced-community-repositories).

That said, this issue is still open for anyone who haven't taken any of our good first issue.

Thank you for your understanding. 😊

**Comment by Woytsekj** [comment]
.take
