### ISSUE TITLE
Bug: Incorrect links and term's consistency on the README

### ISSUE THREAD

**Issue by adiati98** [open-sauced/guestbook#245]
## Description

There are incorrect links in the README. Also, we want to have consistency with the term "guestbook".

## Suggested Solution

- [ ] Change all "guest book" term to "guestbook" on the README. If it starts with capital letter, keep the capital letter.
- [ ] Update links and some wording in the code snippet with the suggestion following the snippet:

   - [ ] https://github.com/open-sauced/guestbook/blob/a425e260c10fbf902db78a497e9b1bff3cdc0990/README.md?plain=1#L12

      ```markdown
      This guestbook is a place for people who have taken [OpenSauced](https://app.opensauced.pizza/)'s [Intro to Open Source course](https://intro.opensauced.pizza/#/) to take their first steps into contributing to open source.
      ```

   - [ ] https://github.com/open-sauced/guestbook/blob/a425e260c10fbf902db78a497e9b1bff3cdc0990/README.md?plain=1#L20

      ```markdown
      If you encounter merge conflicts while contributing to this repository, read our Intro to Open Source course's "[Merge Conflicts in the Guestbook Repository](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=merge-conflicts-in-the-guestbook-repository)" section.
      ```

   - [ ] https://github.com/open-sauced/guestbook/blob/a425e260c10fbf902db78a497e9b1bff3cdc0990/README.md?plain=1#L24

      ```markdown
      You can add this contribution to your [Highlight](https://app.opensauced.pizza/feed) at OpenSauced! Read our docs to learn more about [Highlight feature](https://docs.opensauced.pizza/features/highlights/).
      ```

   - [ ] https://github.com/open-sauced/guestbook/blob/a425e260c10fbf902db78a497e9b1bff3cdc0990/README.md?plain=1#L26

      ```markdown
      Hungry for more contributions? Check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repository and join us in celebrating pizza!🍕
      ```

   - [ ] https://github.com/open-sauced/guestbook/blob/a425e260c10fbf902db78a497e9b1bff3cdc0990/README.md?plain=1#L30

      ```markdown
      All contributors are required to abide by our [Code of Conduct](https://github.com/open-sauced/.github/blob/main/CODE_OF_CONDUCT.md). Please follow our [Contributing Guidelines](CONTRIBUTING.md) for contributing.
      ```

   - [ ] https://github.com/open-sauced/guestbook/blob/a425e260c10fbf902db78a497e9b1bff3cdc0990/README.md?plain=1#L32

      ```markdown
      - **Course improvement**: If you are interested in improving OpenSauced's Intro to Open Source course, please create an issue at our [intro repository](https://github.com/open-sauced/intro) and refer to the [Contributing Guidelines](https://github.com/open-sauced/intro/blob/main/CONTRIBUTING.md).
      ```

**Comment by safaanilatasoy** [comment]
.take

**Comment by BekahHW** [comment]
Hey @safaanilatasoy just wanted to check-in and see how this is going.

**Comment by safaanilatasoy** [comment]
Hi @BekahHW, everthing is good but I sent a pull request, I didn't fully understand what else I need to do.

**Comment by BekahHW** [comment]
@safaanilatasoy there isn't currently a Pull Request (PR) there. Can you double check that you pushed the latest version of your fork and then made the PR on this repo?

**Comment by adiati98** [comment]
Hey @safaanilatasoy,

I've closed your PR and explain the reasons in [the comment there](https://github.com/open-sauced/guestbook/pull/246#issuecomment-2022418630). Please read the comment.

That been said, you need to create 2 new branches:

1. To work on change for this issue.
2. To add yourself to the guestbook.

Once you're done with one thing, create a new pull request, and work on the next. And don't forget to complete the PR form. Incomplete PR form will be marked as invalid and may be closed.

Feel free to ask questions if you need clarifications. Thanks! :)

**Comment by safaanilatasoy** [comment]
@adiati98 Hello, ready for review 🚀  I hope it happened this time 😄 thank you

**Comment by adiati98** [comment]
@safaanilatasoy I left reviews on your PR. Don't hesitate to let me know if you have questions or need any help. 😊
