### ISSUE TITLE
PR Template Link 404 docs

### ISSUE THREAD

**Issue by StackOverflowIsBetterThanAnyAI** [open-sauced/guestbook#265]
The 'Getting Started' link for a 'docs' issue : https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started leads to a 404 error.

**Comment by adiati98** [comment]
Hi @StackOverflowIsBetterThanAnyAI 

Thank you for the report! ✨️

However, this issue has been fixed in #258.

That said, we'll close this issue.
