### ISSUE TITLE
Docs: Fix link in the issue template

### ISSUE THREAD

**Issue by adiati98** [open-sauced/guestbook#271]
> [!IMPORTANT]
> If you've worked on a good first issue in any of our [community repositories](https://docs.opensauced.pizza/contributing/opensauced-maintainers-guide/community-maintainers-guide/#opensauced-community-repositories) before, please refrain from taking this issue.
> We may remove you from the assignees and not accept your pull request if you choose to proceed.

## Description

We had a major update to our Intro to Open Source course that caused the changes of the links.

## Suggested Solution

In the `.github/ISSUE_TEMPLATE/add_contributor.yml`, change the link to the "Getting Started" section in a checkbox's description as follow:

```markdown
https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started.
```

Line that needs to be changed:

https://github.com/open-sauced/guestbook/blob/10db621a076b07dd5c039d45f3adc0f8b410cfe0/.github/ISSUE_TEMPLATE/add_contributor.yml?plain=1#L28

**Comment by prasad-hp** [comment]
I have fixed the issue and committed but the running the "npm run contributors:generate" does not generate my badge on Readme.

**Comment by adiati98** [comment]
Hey @prasad-hp,
I'm assigining this to you.

But for your future reference, please wait to work on any issue and creating PR before it's assigned to you to avoid duplication or rejected PRs. 🙂
