### ISSUE TITLE
Docs: Fix broken links in the README

### ISSUE THREAD

**Issue by adiati98** [open-sauced/guestbook#272]
> [!IMPORTANT]
> If you've worked on a good first issue in any of our [community repositories](https://docs.opensauced.pizza/contributing/opensauced-maintainers-guide/community-maintainers-guide/#opensauced-community-repositories) before, please refrain from taking this issue.
> We may remove you from the assignees and not accept your pull request if you choose to proceed.

## Description

WIth the major update to the Intro to Open Source course, the links on the website are also changed. So, we need to update the links to the course in the README of guestbook repo.

## Suggested Solution

Below, you will find the lines that need to be updated and how they need to be updated.

- [x] https://github.com/open-sauced/guestbook/blob/10db621a076b07dd5c039d45f3adc0f8b410cfe0/README.md?plain=1#L12
   
   ```markdown
   [Intro to Open Source course](https://intro.opensauced.pizza/#/intro-to-oss/README)
   ```

- [x] https://github.com/open-sauced/guestbook/blob/10db621a076b07dd5c039d45f3adc0f8b410cfe0/README.md?plain=1#L16

   ```markdown
   "[Let's Get Practical](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=let39s-get-practical)"
   ```

- [x] https://github.com/open-sauced/guestbook/blob/10db621a076b07dd5c039d45f3adc0f8b410cfe0/README.md?plain=1#L20

   ```markdown
   "[Merge Conflicts in the Guestbook Repository](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=merge-conflicts-in-the-guestbook-repository)"
   ```

- https://github.com/open-sauced/guestbook/blob/10db621a076b07dd5c039d45f3adc0f8b410cfe0/README.md?plain=1#L32

   ```markdown
   [Contributing Guidelines](https://github.com/open-sauced/intro/blob/main/docs/CONTRIBUTING.md)
   ```

**Comment by the1Riddle** [comment]
Hello
you can Assign me for the task, am willing to help with the appdate

**Comment by the1Riddle** [comment]
.take
