### ISSUE TITLE
Feature: Add @michaella23 as a contributor

### ISSUE THREAD

**Issue by michaella23** [open-sauced/guestbook#295]
### Description

As part of the Intro to Open Source course, we are encouraged to contribute to this repo. I am making a contribution and building in public.

### Suggested solution

Add myself as a contributor.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Getting Started Instructions

- [X] I agree to follow this project's Getting Started instructions

**Comment by michaella23** [comment]
Hello. I am walking through the steps of "Let's Get Practical" and was also trying to create a video of myself making a contribution to the repository. I've run into a problem though, and I don't quite have the know-how to resolve it.This is the error message I receive when using `npm run add:contributors`. I wonder if you could advise please. Thank you.

![Screen Shot 2024-05-08 at 5 04 28 PM](https://github.com/open-sauced/guestbook/assets/89760083/a1530294-ff1d-44f4-8411-6b534c85d798)

**Comment by adiati98** [comment]
Hey @michaella23 

I'm not at my computer anymore, and I'm looking at this from my mobile.

I think this would be the problem.

Can you try to add a `{` after line 1841? I think the object is missing the opening curly bracket.

Then run the `npm run contributors:add` again.

Please let me know if the problem still persists so I can take a look at it closer tomorrow. 😊

**Comment by michaella23** [comment]
Thank you @adiati98! I bet that is it. I'm going to try again. 🙂
