### ISSUE TITLE
Feature: Add contributors jiuyueshenhua

### ISSUE THREAD

**Issue by jiuyueshenhua** [open-sauced/guestbook#302]
### Description

hello , I am a beginner, i am very happy to jump my first step!
btw,the website [Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) is 404.

### Suggested solution

Add myself as a contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Getting Started Instructions

- [X] I agree to follow this project's Getting Started instructions

**Comment by adiati98** [comment]
Hey @jiuyueshenhua,

Where do you find the broken link?
If it's on the issue form, it's fixed not long ago.

**Comment by adiati98** [comment]
Thanks for the information, @jiuyueshenhua!

We do have [an issue open to fix the links on our README](https://github.com/open-sauced/guestbook/issues/272). 🙂
