### ISSUE TITLE
Feature: Add @the1Riddle as a contributor

### ISSUE THREAD

**Issue by the1Riddle** [open-sauced/guestbook#316]
### Description

Addition of a new contributor as part of the Intro to Open Source course.

### Suggested solution

Add a contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Getting Started Instructions

- [X] I agree to follow this project's Getting Started instructions

**Comment by adiati98** [comment]
Hey @the1Riddle,

As your issue hasn't been worked on for some time, we're closing it.
Feel free to open a new issue and work on it if you'd still like to contribute. ✨
