### ISSUE TITLE
Feature: Add @mudzoj as a contributorFeature:

### ISSUE THREAD

**Issue by mudzoj** [open-sauced/guestbook#331]
### Description

As a beginner in contributing to Open Source projects, I have been encouraged to contribute to this beginner repo.

### Suggested solution

Adding myself as a contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Getting Started Instructions

- [X] I agree to follow this project's Getting Started instructions

**Comment by adiati98** [comment]
Hey @mudzoj,

As your issue hasn't been worked on for some time, we're closing it.
Feel free to open a new issue and work on it if you'd still like to contribute. ✨
