### ISSUE TITLE
Docs: Update the Contributing Guidelines

### ISSUE THREAD

**Issue by adiati98** [open-sauced/guestbook#362]
## Description

As part of Intro to OSS course, the contributing guidelines in this guestbook repo is following and being adjusted from the guidelines at the intro repository. But as the intro repository evolves, the contributing guidelines in this repo is no longer 100% accurate. Therefore, it needs to be updated.

Another reason is as Hacktoberfest is approaching, we want to make this repo ready for contributions not only from the course participants, but also from folks who don't take our Intro to OSS course.

### Alternative 1

Update the contributing guidelines by adding instructions from [Let's Get Practical](https://opensauced.pizza/learn/intro-to-oss/how-to-contribute-to-open-source?id=let39s-get-practical) section and adjust other sections accordingly.

### Alternative 2

Remove the contributing guidelines completely with below reasons:

- We have the [Getting Started](https://opensauced.pizza/learn/intro-to-oss/how-to-contribute-to-open-source?id=let39s-get-practical) section on the README that navigate folks to the instructions of adding themselves to the guestbook.
- The [Contributing](https://github.com/open-sauced/guestbook?tab=readme-ov-file#-contributing) section on the README already holds the information for folks to improve our Intro to OSS course.

**Comment by adiati98** [comment]
@BekahHW I need your thoughts on this. Thank you.

**Comment by BekahHW** [comment]
@adiati98 Let's go with Alternative 1 and reduce the need to update in multiple places. We can link in the readme and make sure to mention that this is part of a course, so we recommend that you complete the course.

**Comment by adiati98** [comment]
> @adiati98 Let's go with Alternative 1 and reduce the need to update in multiple places. We can link in the readme and make sure to mention that this is part of a course, so we recommend that you complete the course.

Just to confirm here, @BekahHW. Alternative 1 is basically proposing to copy-paste the [Let's Get Practical](https://opensauced.pizza/learn/intro-to-oss/how-to-contribute-to-open-source?id=let39s-get-practical) content to replace the content in the CONTRIBUTING file.

**Comment by BekahHW** [comment]
@adiati98, whoops. I was thinking just linking to the Getting Practical section and not copy pasting.

I do think we still want to talk about issues and communication style here. But I don't feel super strongly about whether or not to have the contributing guide. I might lean towards keeping it, only bc I think it makes for a good example of what to expect in an open source project.

**Comment by BekahHW** [comment]
@adiati98 yes, this sounds like a good plan!

**Comment by adiati98** [comment]
Hey @BekahHW,

I just realized that the all information in the "Issues" section in the contributing guidelines is pointing to the "intro" repo, and not "guestbook".

Also, at guestbook, we don't apply the `.take` action. We might want to remove this section. Or do you have any other thoughts?

**Comment by BekahHW** [comment]
@adiati98 Whatever you think is best is fine with me.

**Comment by adiati98** [comment]
@BekahHW we don't have many issues in this repo. So, I'll update it to ask for permission before working on issues rather than use the `.take`.
