### ISSUE TITLE
Docs: Remove the translation guidelines

### ISSUE THREAD

**Issue by adiati98** [open-sauced/guestbook#363]
## Description

As this repository is completely to add contributors to the guestbook with minimum information and we're moving translations at the Open Sauced Education Path to be Community Translations, we don't need to translate anything here. Therefore, the translation guidelines is not necessary.

## Suggested Solution

- Remove the `i18n-guidelines.md`.
- Remove the "Translations" list from the [Contributing](https://github.com/open-sauced/guestbook?tab=readme-ov-file#-contributing) section on the README.

**Comment by DevJSter** [comment]
.take

**Comment by adiati98** [comment]
Hey @DevJSter ,
Thank you for your interest in this issue.

However, this issue is currently still on triage, so please refrain from working on it. Thank you.

**Comment by BekahHW** [comment]
@adiati98 that makes sense.
