### ISSUE TITLE
Feature: Add @Kratosgado as a contributor

### ISSUE THREAD

**Issue by Kratosgado** [open-sauced/guestbook#387]
### Description

As part of the Open Source course, we are encouraged to contribute to this repository.

### Suggested solution

Added myself as a contributer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Getting Started Instructions

- [X] I agree to follow this project's Getting Started instructions

**Comment by adiati98** [comment]
Hey @Kratosgado,

As your issue hasn't been worked on for some time, we're closing it.
Feel free to open a new issue and work on it if you'd still like to contribute. ✨
