### ISSUE TITLE
Feature: Add @aysh34 as a contributor

### ISSUE THREAD

**Issue by aysh34** [open-sauced/guestbook#399]
### Description

As part of the intro to open source course, we are encouraged to contribute to this repo.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Getting Started Instructions

- [X] I agree to follow this project's Getting Started instructions

**Comment by adiati98** [comment]
Hey @aysh34,

As your issue hasn't been worked on for some time, we're closing it.
Feel free to open a new issue and work on it if you'd still like to contribute. ✨
