### ISSUE TITLE
Feature: Add anirudhmehra2005 as a contributor

### ISSUE THREAD

**Issue by anirudhmehra2005** [open-sauced/guestbook#411]
### Description

As a part of learning opensource, we are encouraged for this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Getting Started Instructions

- [X] I agree to follow this project's Getting Started instructions

**Comment by adiati98** [comment]
Hey @anirudhmehra2005,

As your issue hasn't been worked on for some time, we're closing it.
Feel free to open a new issue and work on it if you'd still like to contribute. ✨
