### ISSUE TITLE
Feature: Add @3x10RaiseTo8 as a contributor

### ISSUE THREAD

**Issue by 3x10RaiseTo8** [open-sauced/guestbook#431]
### Description

As part of the Intro to Open Source course, we are encouraged to contribute to this repo. Fake accomplishment.

### Suggested solution

Add myself as a contributor.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Getting Started Instructions

- [X] I agree to follow this project's Getting Started instructions

**Comment by BekahHW** [comment]
@3x10RaiseTo8 I want to push back against the "Fake accomplishment" thought here. 

1. How do you define accomplishment?
2. I would like to emphasize that this PR prepares contributors to clone, fork, write issues, and submit a PR. So contributors are learning to participate in the open source lifecycle. This prepares them to contribute to other repositories and be good open source citizens.
