### ISSUE TITLE
Feature: Add @nobleststriver as a contributor

### ISSUE THREAD

**Issue by nobleststriver** [open-sauced/guestbook#435]
### Description

Doing this as part of the Intro to Open Source course.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Getting Started Instructions

- [X] I agree to follow this project's Getting Started instructions

**Comment by adiati98** [comment]
Hey @nobleststriver,

As your issue hasn't been worked on for some time, we're closing it.
Feel free to open a new issue and work on it if you'd still like to contribute. ✨
