### ISSUE TITLE
Feature: Add @CarlosCordobaR as contributor

### ISSUE THREAD

**Issue by CarlosCordobaR** [open-sauced/guestbook#470]
### Description

As parto of the Intro to Open Source course, we encouraged to contribute to this repo

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Getting Started Instructions

- [X] I agree to follow this project's Getting Started instructions

**Comment by adiati98** [comment]
Hey @CarlosCordobaR,

As your issue hasn't been worked on for some time, we're closing it.
Feel free to open a new issue and work on it if you'd still like to contribute. ✨
