### ISSUE TITLE
Docs: Fix links in the README

### ISSUE THREAD

**Issue by adiati98** [open-sauced/guestbook#471]
> [!IMPORTANT]
> If you've worked on a good first issue in any of our [community repositories](https://docs.opensauced.pizza/contributing/opensauced-maintainers-guide/community-maintainers-guide/#opensauced-community-repositories) before, please refrain from taking this issue.
> We may remove you from the assignees and not accept your pull request if you choose to proceed.

## Description

We have changed the link to our courses' website. So, we need to update the links to the course in the README of the guestbook repo.

## Suggested Solution

Below, you will find the lines that need to be updated and how they need to be updated.

- [ ] https://github.com/open-sauced/guestbook/blob/f539a0c3d65610b4a82d3c3781ca0f85932ce6ef/README.md?plain=1#L12
   
   ```markdown
   [Intro to Open Source course](https://opensauced.pizza/learn/intro-to-oss/)
   ```

- [ ] https://github.com/open-sauced/guestbook/blob/10db621a076b07dd5c039d45f3adc0f8b410cfe0/README.md?plain=1#L16

   ```markdown
   "[Let's Get Practical](https://opensauced.pizza/learn/intro-to-oss/how-to-contribute-to-open-source#lets-get-practical)"
   ```

- [ ] https://github.com/open-sauced/guestbook/blob/10db621a076b07dd5c039d45f3adc0f8b410cfe0/README.md?plain=1#L20

   ```markdown
   "[Merge Conflicts in the Guestbook Repository](https://opensauced.pizza/learn/intro-to-oss/how-to-contribute-to-open-source#merge-conflicts-in-the-guestbook-repository)"
   ```

- [ ] https://github.com/open-sauced/guestbook/blob/10db621a076b07dd5c039d45f3adc0f8b410cfe0/README.md?plain=1#L32

   ```markdown
   [Contributing Guidelines](https://github.com/open-sauced/intro/blob/main/contributing/CONTRIBUTING.md)
   ```

**Comment by Harshh18** [comment]
Kindly assign me this issue, I would love to contribute to this repository.

**Comment by Harshh18** [comment]
Okay, thank you, I'll start working on this
