### ISSUE TITLE
Docs: Add information to write PR details 

### ISSUE THREAD

**Issue by adiati98** [open-sauced/guestbook#521]
> [!IMPORTANT]
> If you've worked on any issue and/or an issue with `good first issue` label in any of our [community repositories](https://docs.opensauced.pizza/contributing/opensauced-maintainers-guide/community-maintainers-guide/#opensauced-community-repositories) before, please refrain from taking this issue.
> We may remove you from the assignees and not accept your pull request if you choose to proceed.

## Description

We see some contributors wrote their PR description and/or related issue in the comments, which are hidden in preview mode. This causes maintainers and the bot don't see this info when they review the PR. We need to add information to write PR details outside the comments in the PR template.

Another thing is some contributors use the example issue number in the comment and not their own. We need to clarify this.

## Suggested Solution

Below are the lines that need to be updated and how they need to be updated.

- [ ] https://github.com/open-sauced/guestbook/blob/90b5a328a17e396157a217ee67b7882bb617a098/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L5-L8

   ```markdown
   <!--
   Please do not leave this blank. Add your description **below** this line and **outside** of the comment tags.
   For example: This PR adds <your-github-username> as a contributor.
   -->
   ```

- [ ]  https://github.com/open-sauced/guestbook/blob/90b5a328a17e396157a217ee67b7882bb617a098/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L17-L20

   ```markdown
   <!-- 
   Add your related issue **below** this line and **outside** of the comment tags.

   Please use this format to link your issue: Closes #XXX.
   Change "XXX" to your issue number that you can find next to your issue's title.
   
   More information about link issue: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword 
   -->

**Comment by Brijeshthummar02** [comment]
sure i can do it. assign me
