### ISSUE TITLE
Feature: Translate guestbook directions into other languages

### ISSUE THREAD

**Issue by CBID2** [open-sauced/guestbook#79]
### Type of feature

🍕 Feature

### Current behavior

The guestbook directions are written only in English, which can make new open source contributors, especially those who have English as a second language or do not speak it all.  

### Suggested solution

In the spirit of @antonio-pedro99's suggestion in [issue #16 of the intro course's repo](https://github.com/open-sauced/intro/issues/16), I think it would be helpful to have the directions for the guestbook in Portuguese. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
> @CBID2, because this isn't docsify, we might need to approach it in a different way. Do you have a suggestion for how to do that?
> 
> 

#Hi @BekahHW. Great question. I think we can create a sidebar and add a translation feature button.

**Comment by BekahHW** [comment]
@CBID2 here's my suggestion: we make a folder structure that's linked in the ReadMe for the translations. Along with that, we have an issue that's always up that's for translations--we can ask people to comment on the language they would like to work on, and we can add a note that the translations are not actively maintained by the maintainers, but by contributors.

So, the folder structure would look like this:

`Translations` - This folder holds a README.md that links to folders for each of the translations. 

## Translations > README
Welcome to our Guestbook translations! Below, you'll find links to the folders of all the translations we currently have. If you'd like to add a translation, check out [this issue](). 

- [French](links to french folder)
- [Portuguese](links to Portuguese folder)

____

## French Folder
     - README.md (this is the file that has the translation)


With all that said, I think we should wait for @adiati98's PR, bc we can't translate the CLI, but we can translate manual changes.

One thing we need to note is that the info they put in must be in English and appear as exactly as it appears for other contributors. Meaning, the spelling can't change. (It breaks the CLI too--ask me how I found out, lol).

**Comment by CBID2** [comment]
> @CBID2 here's my suggestion: we make a folder structure that's linked in the ReadMe for the translations. Along with that, we have an issue that's always up that's for translations--we can ask people to comment on the language they would like to work on, and we can add a note that the translations are not actively maintained by the maintainers, but by contributors.
> 
> 
> 
> So, the folder structure would look like this:
> 
> 
> 
> `Translations` - This folder holds a README.md that links to folders for each of the translations. 
> 
> 
> 
> ## Translations > README
> 
> Welcome to our Guestbook translations! Below, you'll find links to the folders of all the translations we currently have. If you'd like to add a translation, check out [this issue](). 
> 
> 
> 
> - [French](links to french folder)
> 
> - [Portuguese](links to Portuguese folder)
> 
> 
> 
> ____
> 
> 
> 
> ## French Folder
> 
>      - README.md (this is the file that has the translation)
> 
> 
> 
> 
> 
> With all that said, I think we should wait for @adiati98's PR, bc we can't translate the CLI, but we can translate manual changes.
> 
> 
> 
> One thing we need to note is that the info they put in must be in English and appear as exactly as it appears for other contributors. Meaning, the spelling can't change. (It breaks the CLI too--ask me how I found out, lol). 
> 
> 

Great idea @BekahHW! :) We should also wait for French PR that I did with Geoffrey

**Comment by CBID2** [comment]
By the way @BekahHW, @antonio-pedro99 did the Portuguese translation, not @adiati98 lol 😂

**Comment by BekahHW** [comment]
@CBID2 I know. I was referring to Ayu's PR for [this issue](https://github.com/open-sauced/guestbook/issues/81)

**Comment by CBID2** [comment]
> @CBID2 I know. I was referring to Ayu's PR for [this issue](https://github.com/open-sauced/guestbook/issues/81)

Ohh thanks for clarifying @BekahHW 🤦🏾‍♀️

**Comment by adiati98** [comment]
> By the way @BekahHW, @antonio-pedro99 did the Portuguese translation, not @adiati98 lol 😂

I think Bekah mentioned issue #81, @CBID2 😄

**Comment by CBID2** [comment]
> > By the way @BekahHW, @antonio-pedro99 did the Portuguese translation, not @adiati98 lol 😂
> 
> I think Bekah mentioned issue #81, @CBID2 😄

Yeah I get it now @adiati98.😊 How are you doing with your PR by the way?

**Comment by adiati98** [comment]
> > > By the way @BekahHW, @antonio-pedro99 did the Portuguese translation, not @adiati98 lol 😂
> > 
> > I think Bekah mentioned issue #81, @CBID2 😄
> 
> Yeah I get it now @adiati98.😊 How are you doing with your PR by the way?

The issue just got the green light today. So I haven't worked on it yet as I was outside the whole day 🙂

**Comment by CBID2** [comment]
> > > > By the way @BekahHW, @antonio-pedro99 did the Portuguese translation, not @adiati98 lol 😂
> > > 
> > > I think Bekah mentioned issue #81, @CBID2 😄
> > 
> > Yeah I get it now @adiati98.😊 How are you doing with your PR by the way?
> 
> The issue just got the green light today. So I haven't worked on it yet as I was outside the whole day 🙂

Ah great. I always find myself to be more focused after exercising outside

**Comment by geoffreylgv** [comment]
> @CBID2 here's my suggestion: we make a folder structure that's linked in the ReadMe for the translations. Along with that, we have an issue that's always up that's for translations--we can ask people to comment on the language they would like to work on, and we can add a note that the translations are not actively maintained by the maintainers, but by contributors.
> 
> So, the folder structure would look like this:
> 
> `Translations` - This folder holds a README.md that links to folders for each of the translations.
> 
> ## Translations > README
> Welcome to our Guestbook translations! Below, you'll find links to the folders of all the translations we currently have. If you'd like to add a translation, check out this issue.
> 
> * [French](links to french folder)
> * [Portuguese](links to Portuguese folder)
> 
> ## French Folder
> ```
>  - README.md (this is the file that has the translation)
> ```
> 
> With all that said, I think we should wait for @adiati98's PR, bc we can't translate the CLI, but we can translate manual changes.
> 
> One thing we need to note is that the info they put in must be in English and appear as exactly as it appears for other contributors. Meaning, the spelling can't change. (It breaks the CLI too--ask me how I found out, lol).

For the project structure related to the translations, we can have like @BekahHW said, `Translations` folder, and inside have  a folder named language country (`fr` for Français or `pt` for Portuguese) `/Translations/fr/README.md`

Also, in the `fr` folder, we should have the `navbar/sidebar` in the specific language.

**Comment by CBID2** [comment]
Hey @BekahHW! 😊 Once and if we get more volunteers to translate, OpenSauced should definitely consider implementing Crowdin. One of the translate leads from FreecodeCamp has shown me how they implement it: https://contribute.freecodecamp.org/#/how-to-translate-files

**Comment by BekahHW** [comment]
@CBID2 I did look into Crowdin. I think we need to make sure there's interest. I'm super excited to have folks interested in translating, but we need to gauge how many people are _using_ the translated versions as part of the discussion. Maybe we should consider adding something to the PR template to ask them to select the language they used to complete the task.
