### ISSUE TITLE
Feature: Steps to edit the `.all-contributorsrc` file

### ISSUE THREAD

**Issue by adiati98** [open-sauced/guestbook#81]
### Type of feature

🍕 Feature

### Current behavior

This repository is using CLI to add contributors to the `README.md` file.

However, there is also a suggestion in the README:

> ... we recommend actually editing the `.all-contributorsrc` file to get more experience with pull requests and reviews.

Does this mean that we are suggesting contributors to add themselves manually in the file? 

### Suggested solution

If we want to encourage contributors to add themselves manually to the file, we also want to provide instructions on how to do so.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by adiati98** [comment]
@BekahHW if you agree with this, I would love to be assigned for this issue. I want to wait for the green light before assigning myself to this.

Thank you! 😄

**Comment by BekahHW** [comment]
Thanks, @adiati98! It's all you.

**Comment by adiati98** [comment]
@BekahHW I'm working on the changes atm.

After our last discussion, I researched more about adding and updating contributor's profile.

And here are the new findings:

- When we add (or update) ourselves to the list with CLI, pressing enter will automatically add and commit our changes. That's why when we run `git status`, we get a `nothing to commit, working tree clean` message. But when we run `git log`, we see the automated commit. For example, `docs: add @adiati98 as a contributor`. So, working on changes can be done in a new or `main` branch.
- We don't need to add and commit our changes when we use the CLI, but we must do so when manually updating the file.

Based on this, do we want to add a step to create a branch, or do we want contributors to work on changes directly in the `main` branch?

**Comment by adiati98** [comment]
> Thanks for investigating this. I think that explanation needs to be contained in the documentation for adding yourself. 
> 
> If folks are manually adding yourself, then you should create a new branch bc those are best practices. 
> 
> Does that answer the question?

Yes. I've drafted the docs to include and encourage folks to create a new branch. Adding themselves through CLI can also be done in a new branch.

But let me see where it is best to put the explanation that adding themselves through CLI doesn't require adding and committing changes. This is the only difference with adding themselves manually. 

I'm working on it! 😊
